select * from customer limit 50

-- 1. Revenue by Gender – Compared total revenue generated by male vs. female customers.
select gender, sum(purchase_amount) as revenue
from customer 
group by gender

-- 2. High-Spending Discount Users – Identified customers who used discounts but still spent above the average purchase amount.
select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG ( purchase_amount ) from customer)

-- 3. Top 5 Products by Rating – Found products with the highest average review ratings.
Select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Rating Product"
from customer
group by item_purchased
order by avg(review_rating)
limit 5;

-- 4. Shipping Type Comparison – Compared average purchase amounts between Standard and Express shipping
SELECT shipping_type,
       ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
WHERE LOWER(shipping_type) IN ('standard','express')
GROUP BY shipping_type;

-- 5. Subscribers vs. Non-Subscribers – Compared average spend and total revenue across subscription status.
Select subscription_status,
COUNT (customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as total_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_spend,total_revenue desc;

-- 6. Discount-Dependent Products – Identified 5 products with the highest percentage of discounted purchases.
SELECT item_purchased,
       ROUND( 100.0 * SUM( CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2 ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Customer Segmentation – Classified customers into New, Returning, and Loyal segments based on purchase history
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- 8. Top 3 Products per Category – Listed the most purchased products within each category.
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3

-- 9. Repeat Buyers & Subscriptions – Checked whether customers with >5 purchases are more likely to subscribe.
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. Revenue by Age Group – Calculated total revenue contribution of each age group.
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
